version: '3.8'

services:
  api:
    build: .
    container_name: yt-sentiment-api
    ports:
      - "8003:8003"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8003/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s


